/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.ayarlar.ActionAyarlari;
import gui.ayarlar.ButtonAyarlari;
import gui.ayarlar.IDuzenleyici;
import gui.ayarlar.TextAyarlari;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author mertf
 */
public class BasvuruEkrani extends javax.swing.JFrame implements IDuzenleyici{

    /**
     * Creates new form BasvuruEkrani
     */
    public BasvuruEkrani() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basvuruEkraniPanel = new javax.swing.JPanel();
        adSoyadLabel = new javax.swing.JLabel();
        adSoyadText = new javax.swing.JTextField();
        tcNoLabel = new javax.swing.JLabel();
        tcNoText = new javax.swing.JTextField();
        telNoText = new javax.swing.JTextField();
        telNoLabel = new javax.swing.JLabel();
        kisiselBilgilerLabel1 = new javax.swing.JLabel();
        guvenlikSorusuLabel = new javax.swing.JLabel();
        guvenlikSorusu = new javax.swing.JComboBox();
        guvenlikCevapLabel = new javax.swing.JLabel();
        guvenlikCevapText = new javax.swing.JTextField();
        basvurButton = new javax.swing.JButton();
        backIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register - EncomBank");

        basvuruEkraniPanel.setBackground(new java.awt.Color(153, 204, 255));
        basvuruEkraniPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adSoyadLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        adSoyadLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adSoyadLabel.setText("Name & Surname :");
        basvuruEkraniPanel.add(adSoyadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 90, -1, 40));

        adSoyadText.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        basvuruEkraniPanel.add(adSoyadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 224, 40));

        tcNoLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        tcNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tcNoLabel.setText("TC Identity :");
        basvuruEkraniPanel.add(tcNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 143, -1, 40));

        tcNoText.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        basvuruEkraniPanel.add(tcNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 143, 224, 40));

        telNoText.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        basvuruEkraniPanel.add(telNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 196, 224, 40));

        telNoLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        telNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telNoLabel.setText("Phone Number :");
        basvuruEkraniPanel.add(telNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 196, -1, 40));

        kisiselBilgilerLabel1.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        kisiselBilgilerLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kisiselBilgilerLabel1.setText("Personal Informations");
        basvuruEkraniPanel.add(kisiselBilgilerLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 13, -1, 59));

        guvenlikSorusuLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        guvenlikSorusuLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guvenlikSorusuLabel.setText("Security Question :");
        basvuruEkraniPanel.add(guvenlikSorusuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 254, -1, 40));

        guvenlikSorusu.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        guvenlikSorusu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "What is your pet's name?", "What is your favorite object?", "Who is your favorite superhero?", "Where do you want to live?" }));
        basvuruEkraniPanel.add(guvenlikSorusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 254, 224, 40));

        guvenlikCevapLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        guvenlikCevapLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guvenlikCevapLabel.setText("Answer :");
        basvuruEkraniPanel.add(guvenlikCevapLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 307, -1, 40));

        guvenlikCevapText.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        basvuruEkraniPanel.add(guvenlikCevapText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 307, 224, 40));

        basvurButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        basvurButton.setText("Register");
        basvurButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        basvurButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                basvurButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                basvurButtonMouseExited(evt);
            }
        });
        basvurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basvurButtonActionPerformed(evt);
            }
        });
        basvuruEkraniPanel.add(basvurButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 365, 104, 38));

        backIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/backIcon.png"))); // NOI18N
        backIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backIconMouseClicked(evt);
            }
        });
        basvuruEkraniPanel.add(backIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basvuruEkraniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basvuruEkraniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void basvurButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basvurButtonMouseEntered
        this.setBgFg(evt.getComponent());
    }//GEN-LAST:event_basvurButtonMouseEntered

    private void basvurButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basvurButtonMouseExited
        this.setOriginalBgFg(evt.getComponent());
    }//GEN-LAST:event_basvurButtonMouseExited

    private void setBgFg(Component c){
        ButtonAyarlari.setBgFg((JButton)c, Color.BLACK, Color.WHITE);
    }
    
    private void setOriginalBgFg(Component c){
        ButtonAyarlari.setOriginalBgFg((JButton)c);
    }
    
    private void basvurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basvurButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Your registration has been accepted.");
        ActionAyarlari.setVisible(this, new GirisEkrani()); //dialogdan sonra anasayfaya dön
    }//GEN-LAST:event_basvurButtonActionPerformed

    private void backIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backIconMouseClicked
        ActionAyarlari.setVisible(this, new GirisEkrani());
    }//GEN-LAST:event_backIconMouseClicked

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null); //ekran ortada
        basvuruEkraniPanel.setFocusable(true); //fokus ayar
        TextAyarlari.setOnlyAlphabetic(adSoyadText);
        TextAyarlari.setOnlyNumber(tcNoText);
        TextAyarlari.setOnlyNumber(telNoText);
        TextAyarlari.setMaxLimit(tcNoText, 11);
        TextAyarlari.setMaxLimit(telNoText, 11);
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasvuruEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adSoyadLabel;
    private javax.swing.JTextField adSoyadText;
    private javax.swing.JLabel backIcon;
    private javax.swing.JButton basvurButton;
    private javax.swing.JPanel basvuruEkraniPanel;
    private javax.swing.JLabel guvenlikCevapLabel;
    private javax.swing.JTextField guvenlikCevapText;
    private javax.swing.JComboBox guvenlikSorusu;
    private javax.swing.JLabel guvenlikSorusuLabel;
    private javax.swing.JLabel kisiselBilgilerLabel1;
    private javax.swing.JLabel tcNoLabel;
    private javax.swing.JTextField tcNoText;
    private javax.swing.JLabel telNoLabel;
    private javax.swing.JTextField telNoText;
    // End of variables declaration//GEN-END:variables
}
